# -*- coding: utf-8 -*-
"""assignment_1_intern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FHpxOSzaImrq6AWf0GqnWO6SLgBd5qiZ
"""

# Area of Rectangle
length = float(input("Enter length: "))
breadth = float(input("Enter breadth: "))
area = length * breadth
print("Area of Rectangle =", area)

# Simple Interest
principal = float(input("Enter Principal Amount: "))
rate = float(input("Enter Rate of Interest: "))
time = float(input("Enter Time (in years): "))
si = (principal * rate * time) / 100
print("Simple Interest =", si)

# Celsius to Fahrenheit
celsius = float(input("Enter temperature in Celsius: "))
fahrenheit = (celsius * 9/5) + 32
print("Temperature in Fahrenheit =", fahrenheit)

# Average of 3 Numbers
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))
average = (num1 + num2 + num3) / 3
print("Average =", average)

# Square and Cube
num = float(input("Enter a number: "))
square = num ** 2
cube = num ** 3
print("Square =", square)
print("Cube =", cube)

# Swapping Without Third Variable
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
a, b = b, a
print("After Swapping:")
print("a =", a)
print("b =", b)

# Student Report Program
# Input student details
name = input("Enter Student Name: ")
roll_no = input("Enter Roll Number: ")
# Input marks
mark1 = float(input("Enter marks of Subject 1: "))
mark2 = float(input("Enter marks of Subject 2: "))
mark3 = float(input("Enter marks of Subject 3: "))
# Calculate total
total = mark1 + mark2 + mark3
# Calculate percentage
percentage = (total / 300) * 100
# Display report
print("\n----- STUDENT REPORT -----")
print("Name:", name)
print("Roll Number:", roll_no)
print("Marks:")
print("Subject 1 =", mark1)
print("Subject 2 =", mark2)
print("Subject 3 =", mark3)
print("Total Marks =", total)
print("Percentage =", percentage, "%")

