# -*- coding: utf-8 -*-
"""assignment_2_intern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tis-WkOIJ5IIWtn8qV0rOxUGzl31lAf2
"""

# Sum of first 10 natural numbers
sum = 0
for i in range(1, 11):
    sum += i
print("Sum of first 10 natural numbers =", sum)

# Factorial of a number
num = int(input("Enter a number: "))
fact = 1
for i in range(1, num + 1):
    fact *= i
print("Factorial =", fact)

# Fibonacci Series
n = int(input("Enter number of terms: "))
a = 0
b = 1
print("Fibonacci Series:")
for i in range(n):
    print(a, end=" ")
    c = a + b
    a = b
    b = c

# Largest among 3 numbers
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))
if num1 >= num2 and num1 >= num3:
    largest = num1
elif num2 >= num1 and num2 >= num3:
    largest = num2
else:
    largest = num3
print("Largest number =", largest)

# Student Result System
# Input student details
name = input("Enter Student Name: ")
roll_no = input("Enter Roll Number: ")
# Input marks of 5 subjects using loop
total = 0
for i in range(1, 6):
    marks = float(input(f"Enter marks of Subject {i}: "))
    total += marks
# Calculate percentage
percentage = total / 5
# Display grade using if-elif-else
if percentage >= 90:
    grade = "A+"
elif percentage >= 80:
    grade = "A"
elif percentage >= 70:
    grade = "B"
elif percentage >= 60:
    grade = "C"
elif percentage >= 50:
    grade = "D"
else:
    grade = "F"
# Display result
print("\n----- STUDENT RESULT -----")
print("Name:", name)
print("Roll Number:", roll_no)
print("Total Marks:", total)
print("Percentage:", percentage, "%")
print("Grade:", grade)

